In [96]:
import numpy as np

In [97]:
class SlidingPuzzle:

    def __init__(self,num_blocos):
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if elemento == estado[i,j]:
                    return i, j
        return None, None

    def verifica_estado(self, atual, objetivo):
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if atual[i,j] != objetivo[i,j]:
                    return False
        return True

    def expande_estados(self, atual):
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        #Cima
        if linha > 0:
            nova_linha = linha - 1
            novo_estado = np.copy(atual)
            bloco_alvo = atual[nova_linha,coluna]
            novo_estado[nova_linha,coluna] = 0
            novo_estado[linha,coluna] = bloco_alvo
            novos_estados.append(novo_estado)

        #Baixo
        if linha < self.num_blocos - 1:
            nova_linha = linha + 1
            novo_estado = np.copy(atual)
            bloco_alvo = atual[nova_linha,coluna]
            novo_estado[nova_linha,coluna] = 0
            novo_estado[linha,coluna] = bloco_alvo
            novos_estados.append(novo_estado)

        #Esquerda
        if coluna > 0:
            nova_coluna = coluna - 1
            novo_estado = np.copy(atual)
            bloco_alvo = atual[linha,nova_coluna]
            novo_estado[linha,nova_coluna] = 0
            novo_estado[linha,coluna] = bloco_alvo
            novos_estados.append(novo_estado)

        #Direita
        if coluna < self.num_blocos - 1:
            nova_coluna = coluna + 1
            novo_estado = np.copy(atual)
            bloco_alvo = atual[linha,nova_coluna]
            novo_estado[linha,nova_coluna] = 0
            novo_estado[linha,coluna] = bloco_alvo
            novos_estados.append(novo_estado)

        return novos_estados


In [98]:
from queue import Queue

class BreadthFirstSearch:

    def __init__(self, problema1):
        self.problema = problema1

    def _verifica_visitados(self, estado, estados_visitados):
        for i in estados_visitados:
            if self.problema.verifica_estado(i, estado):
                return True
        return False

    def busca(self, inicio, fim):
        fila = Queue()
        fila.put(inicio)
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0

        while not fila.empty() and cont_estados < 10000:
            atual = fila.get()
            estados_visitados.append(atual)

            if self.problema.verifica_estado(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1
                print("Visitando Estado", cont_estados)

                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                    if not self._verifica_visitados(i, estados_visitados):
                        fila.put(i)
                        print(i)
        return solucao_encontrada, estados_visitados, cont_estados

In [99]:
start = np.matrix([[2,8,3],[1,6,4],[7,0,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

In [100]:
problema = SlidingPuzzle(3)
bfs = BreadthFirstSearch(problema)

In [101]:
solucao, visitados, passos = bfs.busca(start,target)

if solucao:
    print("Solução encontrada em", passos)
else:
    print("Não Encontrado")

Visitando Estado 1
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 8 3]
 [1 6 4]
 [0 7 5]]
[[2 8 3]
 [1 6 4]
 [7 5 0]]
Visitando Estado 2
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[2 8 3]
 [0 1 4]
 [7 6 5]]
[[2 8 3]
 [1 4 0]
 [7 6 5]]
Visitando Estado 3
[[2 8 3]
 [0 6 4]
 [1 7 5]]
Visitando Estado 4
[[2 8 3]
 [1 6 0]
 [7 5 4]]
Visitando Estado 5
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[2 3 0]
 [1 8 4]
 [7 6 5]]
Visitando Estado 6
[[0 8 3]
 [2 1 4]
 [7 6 5]]
[[2 8 3]
 [7 1 4]
 [0 6 5]]
Visitando Estado 7
[[2 8 0]
 [1 4 3]
 [7 6 5]]
[[2 8 3]
 [1 4 5]
 [7 6 0]]
Visitando Estado 8
[[0 8 3]
 [2 6 4]
 [1 7 5]]
[[2 8 3]
 [6 0 4]
 [1 7 5]]
Visitando Estado 9
[[2 8 0]
 [1 6 3]
 [7 5 4]]
[[2 8 3]
 [1 0 6]
 [7 5 4]]
Visitando Estado 10
[[1 2 3]
 [0 8 4]
 [7 6 5]]
Visitando Estado 11
[[2 3 4]
 [1 8 0]
 [7 6 5]]
Visitando Estado 12
[[8 0 3]
 [2 1 4]
 [7 6 5]]
Visitando Estado 13
[[2 8 3]
 [7 1 4]
 [6 0 5]]
Visitando Estado 14
[[2 0 8]
 [1 4 3]
 [7 6 5]]
Visitando Estado 15
[[2 8 3]
 [1 4 5]
 [7 0 6]]
Visitando Estado 16
[[8 0 3]
 [2 6 4]